# Generated by Django 6.0.2 on 2026-02-21 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbEntries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='dbEntry',
        ),
    ]
