# Generated by Django 6.0.2 on 2026-02-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbEntries', '0002_rename_member_dbentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbentry',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='dbentry',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
