# Generated by Django 6.0.2 on 2026-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbEntries', '0003_dbentry_joined_date_dbentry_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dbentry',
            old_name='firstname',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='dbentry',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='dbentry',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='dbentry',
            name='phone',
        ),
        migrations.AddField(
            model_name='dbentry',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
