# Generated by Django 6.0.2 on 2026-02-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbEntries', '0004_user_rename_firstname_dbentry_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dbEntries.user'),
        ),
    ]
